### ISSUE TITLE
FEATURE: Support for dark mode

### ISSUE THREAD

**Issue by oliverlabs** [martignoni/hugo-notice#30] opened 2024-01-09 14:52 UTC
Could you please add support for dark mode colour schemes for notice boxes?

**Comment by martignoni** [comment] 2024-01-10 22:22
This is dupe of #19, which implemented dark mode.

If your CSS uses `prefers-color-scheme` it'll work automatically. Another way to make it work is to inject class `dark` to the body of your page when dark mode is needed.

Closing as duplicate.

**Closed by martignoni** 2024-01-10 22:22 UTC
